server:
  host: localhost
  port: 3000
  prefix: api/v1

swagger:
  title: API RESTfull Student
  description: API RESTfull Student Registration
  version: 0.0.1
  prefix: api/doc

db:
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: root
  database: db_grupo_a
  charset: utf8mb4
  synchronize: true
  logging: false
