version: "3"

services:
  grupo_a-db:
    image: mysql:5.7
    volumes:
    - ./.docker/mysql:/var/lib/mysql
    ports:
    - $MYSQL_PORT:3306
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
    command: --innodb-use-native-aio=0
