version: "3"

services:
  grupo_a-app:
    build:
      context: ./frontend
    ports:
      - $APP_PORT:8080
    depends_on:
      - grupo_a-api

  grupo_a-api:
    build:
      context: ./backend
    ports:
      - $API_PORT:3000
    depends_on:
      - grupo_a-db

  grupo_a-db:
    image: mysql:5.7
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - $MYSQL_PORT:3306
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
    command: --innodb-use-native-aio=0
